rosbag2_bagfile_information:
  version: 4
  storage_identifier: sqlite3
  relative_file_paths:
    - subset_0.db3
  duration:
    nanoseconds: 150223269868
  starting_time:
    nanoseconds_since_epoch: 1653691982427487786
  message_count: 7735
  topics_with_message_count:
    - topic_metadata:
        name: /uavcan/chassis/motors_rpm_feedback
        type: usr_msgs/msg/MotorsRPM
        serialization_format: cdr
        offered_qos_profiles: "- history: 1\n  depth: 1\n  reliability: 1\n  durability: 2\n  deadline:\n    sec: 9223372036\n    nsec: 854775807\n  lifespan:\n    sec: 9223372036\n    nsec: 854775807\n  liveliness: 1\n  liveliness_lease_duration:\n    sec: 9223372036\n    nsec: 854775807\n  avoid_ros_namespace_conventions: false"
      message_count: 1498
    - topic_metadata:
        name: /motion_control/speed_controller/reference_cmd
        type: geometry_msgs/msg/TwistStamped
        serialization_format: cdr
        offered_qos_profiles: ""
      message_count: 1505
    - topic_metadata:
        name: /fix
        type: sensor_msgs/msg/NavSatFix
        serialization_format: cdr
        offered_qos_profiles: "- history: 1\n  depth: 1\n  reliability: 1\n  durability: 2\n  deadline:\n    sec: 9223372036\n    nsec: 854775807\n  lifespan:\n    sec: 9223372036\n    nsec: 854775807\n  liveliness: 1\n  liveliness_lease_duration:\n    sec: 9223372036\n    nsec: 854775807\n  avoid_ros_namespace_conventions: false"
      message_count: 150
    - topic_metadata:
        name: /imu/data
        type: sensor_msgs/msg/Imu
        serialization_format: cdr
        offered_qos_profiles: ""
      message_count: 4552
    - topic_metadata:
        name: /wifi_geo/fix
        type: sensor_msgs/msg/NavSatFix
        serialization_format: cdr
        offered_qos_profiles: "- history: 1\n  depth: 5\n  reliability: 1\n  durability: 2\n  deadline:\n    sec: 9223372036\n    nsec: 854775807\n  lifespan:\n    sec: 9223372036\n    nsec: 854775807\n  liveliness: 1\n  liveliness_lease_duration:\n    sec: 9223372036\n    nsec: 854775807\n  avoid_ros_namespace_conventions: false"
      message_count: 30
  compression_format: ""
  compression_mode: ""